### ISSUE TITLE
Great article!

### ISSUE THREAD

**Issue by bonatoc** [eezis/quasarfirebasestagingandprod#1]
Thanks, it helped a lot.

Two remarks:

1. You should give more visibility to this. In the Quasar Discord channel, on the Quasar forums, and on github by adding labels, and rename the repo by separating the words with dashes ("quasar-firebase-staging-and-prod-environments"), so Google (and I guess Github's search engine) can pick it up.
2. On Mac OS X, you should recommend to use `yarn global` for the Firebase install, otherwise it stumbles across many problems. Took me a while to find this simplest method.

**Comment by eezis** [comment]
Thanks, I incorporated your suggestions.
